apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wilapp
  template:
    metadata:
      labels:
        app: wilapp
    spec:
      containers:
      - name: wil42playground
        image: wil42/playground:v1
        ports:
        - containerPort: 80
